# Name of our GitHub Actions Workflow
name: Build and Push to Azure Container Registry

# This workflow triggers on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Log in to Azure Container Registry (ACR)
    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
    
    # 4. Build and push the Docker image
    # We will tag the image with the unique GitHub commit SHA
    - name: Build and push Docker image
      run: |
        docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/sentiment-api:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/sentiment-api:${{ github.sha }}

    # 5. Log out of ACR and Azure
    - name: Logout from ACR
      run: |
        az acr logout --name ${{ secrets.ACR_NAME }}
    - name: Logout from Azure
      run: |
        az logout
